# Getting Users
GET {{baseUrl}}/users HTTP/1.1

###
# Creating Users
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
    "email": "dipakbari4@gmail.com",
    "pass": "someRandomPassword",
    "dob": "15th-March-1993"
}

###
# Updating Users
PUT {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
    "some": "content"
}

###
# Deleting Users
DELETE {{baseUrl}}/users HTTP/1.1